# Generated by Django 4.2.16 on 2024-09-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.ForeignKey(default='f1ea2dfe-ae3f-4088-964f-5400121967b4', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='posts.project'),
        ),
    ]
