# Generated by Django 4.2.16 on 2024-09-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
    ]
