# Generated by Django 4.2.10 on 2024-04-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='post',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
