# Generated by Django 4.2.23 on 2025-09-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
    ]
