# Generated by Django 4.2.23 on 2025-09-12 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_remove_post_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text="e.g., 'Python', 'React', 'Machine Learning'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posts_count', models.IntegerField(default=0)),
                ('participants_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the thread', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='day_number',
            field=models.IntegerField(blank=True, help_text='Day number in the 100-day challenge', null=True),
        ),
        migrations.CreateModel(
            name='UserThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_day', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='posts.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_post_at',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.userthread'),
        ),
        migrations.AddIndex(
            model_name='userthread',
            index=models.Index(fields=['user', 'thread'], name='posts_usert_user_id_b6a066_idx'),
        ),
        migrations.AddIndex(
            model_name='userthread',
            index=models.Index(fields=['-last_post_at'], name='posts_usert_last_po_28f0d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userthread',
            unique_together={('user', 'thread')},
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['topic', 'created_by'], name='posts_threa_topic_6cb77f_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-updated_at'], name='posts_threa_updated_9e7e72_idx'),
        ),
    ]
