# Generated by Django 4.2.10 on 2024-04-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
