# Generated by Django 4.2.10 on 2024-04-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_delete_test_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
    ]
