# Generated by Django 4.2.13 on 2024-07-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
